//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joonaxii.ConsoleBulletHell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Joonaxii.ConsoleBulletHell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64
        ///44
        ///0
        ///0
        ///0
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Background_Hills {
            get {
                return ResourceManager.GetString("Background_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///5
        ///0
        ///0
        ///0
        ///½½½+++½½½
        ///½+++¤¤++½
        ///+++++¤+++
        ///½¤++++++½
        ///½½½+++½½½
        ///.
        /// </summary>
        internal static string Background_Moon {
            get {
                return ResourceManager.GetString("Background_Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64
        ///44
        ///0
        ///0
        ///0
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½+½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½+½+½½½½½½½½½½½½½½½½½½½½½½½½½½+½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½+½½½½½½½½
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½
        ///½½½½½½½½½½½½½½½+½½½½½½½+½½½½½½½½½½½½½½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Background_Stars {
            get {
                return ResourceManager.GetString("Background_Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49
        ///44
        ///0
        ///0
        ///0
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½╱─────────╥───────╲½½½½
        ///½½½½½╱──┬─┬┬┬─┬────┬─────╱oooooooooo╠══╦════╗╲½½½
        ///½½½½╱ooo╞═╡│╞═╡oooo│ooo╱oo^^^^^^^^^^║^^╚════╩╗│½½
        ///½½½╱o...╞═╛│╘═╡....│..╱^^^^^^^^^^^^┌╫──┐╒═══╦╣│½½
        ///½½╱┌────┴──┼──┴────┘.╱^^^^^^^^^^^^^│╟╥─@@@@@╬╣│½½
        ///½½├┘.......│........╱^^^^^^^^^^^^^^│╚╬═@@@@═╬╣│½½
        ///½½├┐.....┌─┘.......╱^^^^^^^^┏┅┅┅┅┑^│^╠═╝^^╚═╬╣│½½
        ///½½╲└─────┴────────╱^^^^^^^^^┇@@@@│^│^╠═══╗╔═╬╣│½½
        ///½½½╲_____________╱^^^┌─────╱┇@@@@│^╞═╩╦═╗╚╬═╣║│½½
        ///½½½½½½½½½╱^╲....│^^^^│══════╩╕@@@│^└┐╒╝^╚═╣^╠ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Boss_1 {
            get {
                return ResourceManager.GetString("Boss_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49
        ///44
        ///0
        ///0
        ///0
        ///½½½½½½½½½½½½½½½½½½½½½½½½½½/━━━━━━━━━╥━━━━━━━\½½½½
        ///½½½½½/━━┳━┳┳┳━┳━━━━┳━━━━━/oooooooooo╠══╦════╗\½½½
        ///½½½½/ooo╠═╣┃╠═╣oooo┃ooo/oo^^^^^^^^^^║^^╚════╩╗┃½½
        ///½½½/o***╠═╝┃╚═╣****┃**/^^^^^^^^^^^^┏╬━━┓╔═══╦╣┃½½
        ///½½/┏━━━━╩━━╋━━╩━━━━┛*/^^^^^^^^^^^^^┃╟╥━╳╳╳╳╳╬╣┃½½
        ///½½┣┛*******┃********/^^^^^^^^^^^^^^┃╚╬═╳╳╳╳═╬╣┃½½
        ///½½┣┓*****┏━┛*******/^^^^^^^^┏┅┅┅┅┑^┃^╠═╝^^╚═╬╣┃½½
        ///½½\┗━━━━━╩━━━━━━━━/^^^^^^^^^┇╳╳╳╳┃^┃^╠═══╗╔═╬╣┃½½
        ///½½½\_____________/^^^┏━━━━━/┇╳╳╳╳┃^╠═╩╦═╗╚╬═╣║┃½½
        ///½½½½½½½½½/^\****┃^^^^┃══════╩╗╳╳╳┃^┗┓╔╝^╚═╣^╠ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Boss_1_Damage {
            get {
                return ResourceManager.GetString("Boss_1_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///200,38,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½^^^^½½½½½½½½½^^^^½½½½½½½½½^^^^½½½½½½½½½^^^^½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Boss_Warning {
            get {
                return ResourceManager.GetString("Boss_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///0
        ///0
        ///25
        ///#
        ///.
        /// </summary>
        internal static string Bullet_0 {
            get {
                return ResourceManager.GetString("Bullet_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///3
        ///0
        ///0
        ///24
        ///½^½
        ///^#^
        ///½^½
        ///.
        /// </summary>
        internal static string Bullet_1 {
            get {
                return ResourceManager.GetString("Bullet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///1
        ///0
        ///0
        ///25
        ///¤=&gt;
        ///.
        /// </summary>
        internal static string Bullet_2 {
            get {
                return ResourceManager.GetString("Bullet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///16,10,0,0,0[½½½½½½½½½½½½½½½½...½½½½½½.*********½½*********@.½O********@@@..OO******@@@@@.O*******@@@@@½.********@@@½½*********@.½½½½..***.½½½]
        ///16,10,0,0,0[½½½½½½****½½½½½½½½½½***...**½½½½½½*.*****@@@@**½½*******@@@@@.*½*******@@@@@@@.**.****@@@@@@@@@**.****@@@@@@@@@*½*.****@@@@@@@**½½******@@@@@.*½½½½**..***.**½½½]
        ///16,10,0,0,0[½½½½½½½½½½½½½½½½...½½½½½½.***@@@@@*½½***@@@@@@@.½***@@@@@@@@@..**@@@@@@@@@@@.**@@@@@@@@@@@½.**@@@@@@@@@½½***@@@@@@@.½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bullet_Big {
            get {
                return ResourceManager.GetString("Bullet_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8
        ///6
        ///0
        ///0
        ///0
        ///½½½oo½½½
        ///½o~@@~o½
        ///o~@^^@~o
        ///o~@^^@~o
        ///½o~@@~o½
        ///½½½oo½½½
        ///.
        /// </summary>
        internal static string Bullet_Medium {
            get {
                return ResourceManager.GetString("Bullet_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4
        ///3
        ///0
        ///0
        ///0
        ///½¤¤½
        ///¤::¤
        ///½¤¤½
        ///.
        /// </summary>
        internal static string Bullet_Small {
            get {
                return ResourceManager.GetString("Bullet_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13
        ///9
        ///0
        ///0
        ///0
        ///½½╒═══╦╾½½½½½
        ///½╼┘½½½╟────╮½
        ///½½½╭──╫─┮╾╼┿╾
        ///½½╱╘╦═╝^╞═╦╛½
        ///½&lt;══╣^€^╞═╣½½
        ///½½╲╒╩═╗^╞═╩╕½
        ///½½½╰──╫─┶╾╼┿╾
        ///½╼┐½½½╟────╯½
        ///½½╘═══╩╾½½½½½
        ///.
        /// </summary>
        internal static string Enemy_1 {
            get {
                return ResourceManager.GetString("Enemy_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100
        ///16
        ///0
        ///0
        ///0
        ///½^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^½
        ///^^^^^@@@@@^^^^^@@@^^^^@@^^^^^@@^^^^@@@@@@@^^^^^^^^^^^^^^^^^@@@@^^^@@^^^^^^^@^^^@@@@@@@^^^^@@@@@@^^^^
        ///^^^@@@@@@@@^^^^@^@^^^^@@@^^^@@@^^^^@@@@@@@^^^^^^^^^^^^^^^@@@@@@@^^@@^^^^^^@@^^^@@@@@@@^^^^@@@@@@@^^^
        ///^^@@@^^^^^@^^^^@^@^^^^@@@^^^@@@^^^^@@^^^^^^^^^^^^^^^^^^^^@@^^^@@^^@@^^^^^^@@^^^@@^^^^^^^^^@@^^^@@@^^
        ///^^@@^^^^^^^^^^@@^@@^^^@@@^^^@@@^^^^@@^^^^^^^^^^^^^^^^^^^@@@^^^^@@^^@@^^^^^@^^^^@@^^^^^^^^^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///100,70,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^½½½½½½½½½½½½½½½½½½½½½½½½½½½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HI_Won {
            get {
                return ResourceManager.GetString("HI_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,19,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½#½####½½½½½½½½½½½½½½½½½½½½½½½½½##..#½½½½½½½½½½½½½½½½½½½½½½½½½½####½½½½½½½½½½½½½½½½½½½½½½½½½½½#=##½½½½½½½½½½½½½½½½½½½½½½½½½½½=.##½½½½½½½½½½½½½½½½½½½½½½½½½½½.=##½½½½½½½½½½½½½½½½½½½½½½½½½½½.=#½½½½½½½½½½½½½½½½½½½½½½½½½½½½==##½½½½½½½½½½½½½½½½½½½½½½½½½½½#=##½½½½½½½½½½½½½½½½½½½½½½½½½½½####½½½½½½½½½½½½½½½½½½½½½½½½½½½####½½½½½½½½½½½½½½½½½½½½½½½½½½½##..#½½½½½½½½½½½½½½½½½½½½½½½½½½#½####½½½½½½½½½½½½½½½½½½½½½½½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Contact {
            get {
                return ResourceManager.GetString("Laser_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½#####½½½½½######½½½½½½½½½½½½½½½=====#####======##########½½½½½..........................##½½½==..................=.....##½½½##########################½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½##########################½½½½½=#####======#####====...###½½½½................ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Head_Init {
            get {
                return ResourceManager.GetString("Laser_Head_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,11,0,0,0[#####½½½½½######½½½½½½½½½½½½½½½########################½½½½½½½=====#####======##########½½½½½==....==...........=====###½½½½..........................##½½½..........................##½½½..........................##½½½==..................#===###½½½½=====#####======##########½½½½½########################½½½½½½½#####½½½½½######½½½½½½½½½½½½½½½]
        ///31,11,0,0,0[#½½½½½######½½½½½####½½½½½½½½½½########################½½½½½½½=#####======#####===######½½½½½..==...........==...=...###½½½½................ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Head_Loop {
            get {
                return ResourceManager.GetString("Laser_Head_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½#####################½½½½½½½½½½.....................#½½½½½½½½½=====#####======#####½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½################ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Head_Small {
            get {
                return ResourceManager.GetString("Laser_Head_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½#####½½½½½######½½½½½#####½½½½½=====#####======#####=====#####...............................==..................===.......=###############################½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½###############################=#####======#####=====#####====................ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Init {
            get {
                return ResourceManager.GetString("Laser_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,11,0,0,0[#####½½½½½######½½½½½#####½½½½½###############################=====#####======#####=====#####==....==...........==....======.............................................................................................==..................===.......======#####======#####=====#########################################½½½½½######½½½½½#####½½½½½]
        ///31,11,0,0,0[#½½½½½######½½½½½#####½½½½½###################################=#####======#####=====#####====..==...........==....========.................. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Loop {
            get {
                return ResourceManager.GetString("Laser_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½###############################...............................=====#####======#####=====#####½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///31,11,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½################ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Laser_Small {
            get {
                return ResourceManager.GetString("Laser_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7
        ///7
        ///0
        ///0
        ///0
        ///½╲½½½½½
        ///╭┼─┬─┅½
        ///┿┷┭┴┬╮½
        ///├─┤@╞╪┉
        ///┿┯┵┬┴╯½
        ///╰┼─┴─┅½
        ///½╱½½½½½
        ///.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///16,12,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½██½½½½½½½½½½½½½████½½½½½½½½½½½½████½½½½½½½½½½½½½██½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///16,12,0,0,0[½½½½½½½½½½½½½½½½½½½½½½████½½½½½½½½½½██½██½██½½½½½½½█½█½██½█½█½½½½½½½█½½½½½½█½½½½½½██½█½██½█½██½½½½██½█½██½█½██½½½½½½█½½½½½½█½½½½½½½█½█½██½█½█½½½½½½½██½██½██½½½½½½½½½½████½½½½½½½½½½½½½½½½½½½½½½]
        ///16,12,0,0,0[½½½█½█½██½█½█½½½½½█½██½██½██½█½½½█½█½█½██½█½█½█½½████½½½½½½████½½½½½½½½½½½½½½½½½██ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player_Death {
            get {
                return ResourceManager.GetString("Player_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///3
        ///0
        ///0
        ///-90000
        ///╭─╮
        ///│╳│
        ///╰─╯
        ///1
        ///┭┴┬
        ///┤@╞
        ///┵┬┴.
        /// </summary>
        internal static string Player_Hit_Box {
            get {
                return ResourceManager.GetString("Player_Hit_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///16,12,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½████½½½½½½½½½½½██████½½½½½½½½½████████½½½½½½½½████████½½½½½½½½½██████½½½½½½½½½½½████½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///16,12,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½████½½½½½½½½½½½█½½½½█½½½½½½½½½█½½██½½█½½½½½½½█½½████½½█½½½½½½█½½████½½█½½½½½½½█½½██½½█½½½½½½½½½█½½½½█½½½½½½½½½½½████½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½]
        ///16,12,0,0,0[½½½½½½½½½½½½½½½½½½½½½██████½½½½½½½½██████████½½½½½███½½½½½½███½½½███½½½½½½½½███½½█ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player_Life {
            get {
                return ResourceManager.GetString("Player_Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///16,12,0,0,0[½█½½½½½██½½½½½█½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½████½½½½½½½½½½½██████½½½½½█½½½████████½½½██½½½████████½½½█½½½½½██████½½½½½½½½½½½████½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½█½½½½½██½½½½½█½]
        ///16,12,0,0,0[½½½½½½½██½½½½½½½½½½█½½½██½½½█½½½½½███½████½███½½½½½½██½½½½██½½½½½½½½█½½██½½█½½½½█████½████½██████████½████½█████½½½½█½½██½½█½½½½½½½½██½½½½██½½½½½½███½████½███½½½½½█½½½██½½½█½½½½½½½½½½██½½½½½½½]
        ///16,12,0,0,0[½½½½½½½½½½½½½½½½½½½½½██████½½½½½½½½██████████½½½½½████½██½████½½½███½██½½██½███½½█ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player_Respawn {
            get {
                return ResourceManager.GetString("Player_Respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///100,70,0,0,0[½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½½^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^½½½½½½½½½½½½½½½½½½½½½½½½½½½½½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
    }
}
